### ISSUE TITLE
请教一下，您这个纯前端的作品，是用什么server？

### ISSUE THREAD

**Issue by medmin** [mrcotter/crypto-market#2]
我是一直用nodejs写后端， 
现在用React写前端，把前端资源打包后，就是一个静态的index.js
index.html里引入了这个index.js
然后就不知道下一步咋办了

请问是用一个什么http-server之类的，
还是直接用nginx来做server？

**Comment by mrcotter** [comment]
是的，VPS 使用 http-server，然后 nginx 作 reverse proxy 监听端口。

**Comment by medmin** [comment]
嗯，感谢回复。

应该是这样的，弄一个http-server，然后nginx反向代理。

请问您用的是这个嘛：https://github.com/indexzero/http-server

我在您的package.json没看到具体用的哪个server
难道是angular有自带的server？

**Comment by mrcotter** [comment]
@medmin 系统里安装了 node 和 npm，然后 `npm install http-server -g`

**Comment by medmin** [comment]
感谢指教

Kris Cotter <notifications@github.com> 于 2018年3月8日周四 18:31写道：
